# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you usei file, please restart the server process.

# Site settings
title: Home
email: aliee91@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Innovative web design
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://aliecat.org" # the base hostname & protocol for your site
twitter_username: AlieCat
github_username:  AlieCat

# Build settings
markdown: kramdown
